kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: env-webhook
  labels:
    app: env-webhook
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
