apiVersion: v1
kind: ConfigMap
metadata:
  name: env-webhook
  labels:
    app: env-webhook
data:
  envconfig.yaml: |
    envs:
      - configmapref:
          localobjectreference:
            name: env
    namespaces:
      - test
      - default
      
