namespace: baowj

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml

images:
  - name: env-webhook
    newName: docker.io/baowj/env-webhook
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
